# Generated by Django 5.2.14 on 2026-05-20 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flights', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pricealert',
            name='flight_route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to='flights.flightroute'),
        ),
        migrations.AddField(
            model_name='pricealert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='price_alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='flights.pricealert'),
        ),
        migrations.AddField(
            model_name='pricealert',
            name='threshold',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price_alert', to='flights.threshold'),
        ),
    ]
