# Generated by Django 6.0.3 on 2026-04-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_is_active_user_last_login_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('BASIC_USER', 'Basic User'), ('PREMIUM_USER', 'Premium User')], default='BASIC_USER', max_length=20),
        ),
    ]
