# Generated by Django 6.0.3 on 2026-04-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('NON_ADMIN', 'Non Admin')], default='NON_ADMIN', max_length=20),
        ),
    ]
